---
image:
  repository: quay.io/external_storage/cephfs-provisioner
  tag: v2.1.0-k8s1.11
  pullPolicy: IfNotPresent
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

storageClass:
  # If storage class should be created
  create: true
  # If this storage class should be used as default storage class
  default: true
  # Ceph admin name
  adminId: admin
  # Ceph admin secret name.
  # Should be created manualy in the same namespace as this provisioner
  adminSecretName: cephfs-secret
  # Root directory for persistent volumes on cephfs
  claimRoot: /k8s
  # Human readable names for user and shares
  deterministicNames: true
  # List of ceph monitors IPs with ports
  monitors: 
        - 10.242.144.154:6789
        - 10.242.144.151:6789
        - 10.242.144.16:6789

