apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kuber-prod
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.242.144.154:6789, 10.242.144.151:6789, 10.242.144.16:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: "kube-system"
  pool: kuber-prod
  userId: user
  userSecretName: ceph-secret-user

