{{- if or .Values.statsd.mappingConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}
  labels:
    {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
data:
  {{- with .Values.statsd.mappingConfig }}
  statsd.mappingConf: |-
    {{ . | nindent 4 }}
  {{- end }}
{{- end }}
