apiVersion: v2
name: prometheus-statsd-exporter
description: A Helm chart for prometheus stats-exporter
version: 0.3.0
appVersion: 0.20.0
home: https://github.com/prometheus/statsd_exporter
sources:
  - https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-statsd-exporter
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-statsd-exporter
keywords:
  - statsd
  - prometheus
  - exporter
maintainers:
  - email: d@rovergulf.net
    name: scDisorder
