apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-user-my-test
  namespace: terminal-soft
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  name: k8s-access # name group in AD

