# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
telegram:
  token: "1396058954:AAFaZIepDTql0PT6dq1Edqu5xFD6Wr08j0g"
  chat_id: "-597056946" #not used at the moment

releaseOverride: telegram-terminal-soft
image:
  pullPolicy: Always
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://alertmanager-operated:9093
  additionalHosts:
  commonName:
  externalPort: 9087
  internalPort: 9087

livenessProbe:
  initialDelaySeconds: 15
readinessProbe:
  initialDelaySeconds: 5


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 8Mi
