apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nifi-registry.fullname" . }}-config
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
type: Opaque
data:
  default-database: |-
    {{ .Files.Get "data/nifi-registry-primary.mv.db" | b64enc }}
