apiVersion: v1
appVersion: 4.1.1
description: Hazelcast IMDG is the most widely used in-memory data grid with hundreds
  of thousands of installed clusters around the world. It offers caching solutions
  ensuring that data is in the right place when it’s needed for optimal performance.
home: http://hazelcast.org/
icon: http://hazelcast.com/images/logos/Hazelcast-IMDG-Logo-Orange_Dark_Icon_200px.png
keywords:
- hazelcast
- keyvalue
- in-memory
- database
- caching
kubeVersion: '>=1.14.0-0'
maintainers:
- email: rafal@hazelcast.com
  name: leszko
- email: hasan@hazelcast.com
  name: hasancelik
name: hazelcast
sources:
- https://github.com/hazelcast/hazelcast
version: 3.6.1
