apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alertmanager.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alertmanager.fullname" . }}-headless
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if or (gt .Values.replicaCount 1.0) (.Values.additionalPeers) }}
    - port: 9094
      targetPort: 9094
      protocol: TCP
      name: cluster-tcp
    - port: 9094
      targetPort: 9094
      protocol: UDP
      name: cluster-udp
    {{- end }}
  selector:
    {{- include "alertmanager.selectorLabels" . | nindent 4 }}