apiVersion: v1
appVersion: 1.3.3.22
deprecated: true
description: DEPRECATED - A tool for managing Apache Kafka.
engine: gotpl
home: https://github.com/yahoo/kafka-manager
icon: https://kafka.apache.org/images/logo.png
keywords:
- kafka
- zookeeper
- kafka-manager
kubeVersion: ^1.8.0-0
name: kafka-manager
sources:
- https://github.com/yahoo/kafka-manager
version: 2.3.5
