apiVersion: v1
description: Stackdriver exporter for Prometheus
name: prometheus-stackdriver-exporter
version: 1.8.0
appVersion: 0.11.0
home: https://www.stackdriver.com/
sources:
  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-stackdriver_exporter
keywords:
  - metrics
  - stackdriver
  - monitoring
maintainers:
  - name: apenney
    email: apenney@gmail.com
  - name: rpahli
    email: pahli88@googlemail.com
