apiVersion: v2
appVersion: "v1.2.0"
description: A Helm chart to export the metrics from Kafka in Prometheus format using the kafka-exporter from https://github.com/danielqsj/kafka_exporter
name: prometheus-kafka-exporter
home: https://github.com/danielqsj/kafka_exporter
version: 1.0.0
sources:
  - https://gkarthiks.github.io/helm-charts/charts/prometheus-kafka-exporter
keywords:
  - prometheus
  - kafka
maintainers:
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
  - name: golgoth31
    email: golgoth31@notrenet.com
engine: gotpl
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-kafka-exporter
dependencies:
- name: kafka
  version: "12.6.3"
  repository: https://charts.bitnami.com/bitnami
  condition: kafka.enabled
