apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: elk
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
       beats {
       port => 5044
       }
    }

    filter {
        if [kubernetes][namespace] == "terminal-soft" {
         mutate { 
          add_tag => "tag-terminal-soft" 
          remove_field => ["[agent][name]","[agent][version]","[host][mac]","[host][ip]"] }
        }
       }

    output {
      if "tag-terminal-soft" in [tags] {
        elasticsearch {
            hosts => [ "elasticsearch:9200" ]
            manage_template => false
            index => "terminal-soft-%{+YYYY.MM.dd}"
            ilm_rollover_alias => "terminal-soft"
            ilm_policy => "terminal-soft"

        }
      }
    } 









---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.10.1
        ports:
        - containerPort: 5044
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: config-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-volume
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
---
kind: Service
apiVersion: v1
metadata:
  name: logstash-service
  namespace: elk
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: ClusterIP
