apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-snapshot-dir
  namespace: elk
  labels:
   app: elasticsearch-snapshot 
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
