apiVersion: v1
description: A Helm chart for prometheus mysql exporter with cloudsqlproxy
name: prometheus-mysql-exporter
version: 1.1.0
home: https://github.com/prometheus/mysqld_exporter
appVersion: v0.12.1
sources:
  - https://github.com/prometheus/mysqld_exporter
maintainers:
  - name: juanchimienti
    email: juan.chimienti@gmail.com
  - name: monotek
    email: monotek23@gmail.com
